### ISSUE TITLE
Couldn't communicate with a helper application

### ISSUE THREAD

**Issue by dupppp** [OpenEmu/BSNES-Core#2]
I have tried adding bsnes 114 and 115 to openemu, system files for bsnes are added, when i try to switch from snes to bsnes it crashes and says "couldn't communicate with a helper application"
I am running macOS 10.12.16 Sierra and openemu experimental 2.0.9.1. I guess it doesnt work for this version?
I have been trying to look for the crash log, but cant find it.

**Comment by clobber** [comment]
This core plugin requires a minimum of macOS 10.14. It it worked for OpenEmu 2.0.9.1, you'd see it available in the Cores Preferences for download...
